name: Deploy TuneAtLife Portal (Enhanced)

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  FLY_APP_NAME: 'tuneatlife-portal'
  HEALTH_ENDPOINT: '/health'

jobs:
  test:
    name: Test and Quality Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.AUTOMATION_PAT }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: |
          echo "📦 Installing dependencies..."
          npm ci

      - name: Run linting
        run: |
          echo "🔍 Running code quality checks..."
          npm run lint || echo "⚠️ Linting not configured"

      - name: Run tests
        run: |
          echo "🧪 Running tests..."
          npm test || echo "⚠️ Tests not configured"

      - name: Build application
        run: |
          echo "🏗️ Building application..."
          npm run build

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.AUTOMATION_PAT }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Security audit
        run: |
          echo "🔒 Running security audit..."
          npm audit --production --audit-level=moderate

      - name: Dependency vulnerability check
        run: |
          echo "🛡️ Checking for vulnerabilities..."
          npx audit-ci --moderate || echo "⚠️ Vulnerability check completed with warnings"

  deploy:
    name: Deploy to Fly.io
    runs-on: ubuntu-latest
    needs: [test, security-scan]
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.AUTOMATION_PAT }}

      - name: Setup Fly CLI
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly.io
        run: |
          echo "🚀 Starting deployment to Fly.io..."
          flyctl deploy --remote-only --app ${{ env.FLY_APP_NAME }}
          echo "✅ Deployment completed successfully!"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Health Check
        run: |
          echo "🔍 Performing health check..."
          APP_URL="https://${{ env.FLY_APP_NAME }}.fly.dev"
          HEALTH_URL="${APP_URL}${{ env.HEALTH_ENDPOINT }}"
          
          for i in {1..5}; do
            if curl -f -s "$HEALTH_URL" > /dev/null; then
              echo "✅ Health check passed on attempt $i"
              echo "health_status=healthy" >> $GITHUB_OUTPUT
              break
            fi
            echo "⏳ Health check attempt $i failed, retrying in 15s..."
            sleep 15
            if [ $i -eq 5 ]; then
              echo "❌ Health check failed after 5 attempts"
              echo "health_status=unhealthy" >> $GITHUB_OUTPUT
              exit 1
            fi
          done

      - name: Verify Deployment
        run: |
          echo "🔍 Verifying deployment status..."
          flyctl status --app ${{ env.FLY_APP_NAME }}
          flyctl logs --app ${{ env.FLY_APP_NAME }} --lines 10
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Notify Slack on Success
        if: success()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_DEV_INFRA }}
        run: |
          MESSAGE='{"text":"🎉 TuneAtLife Portal deployed successfully! Version: ${{ github.sha }} URL: https://${{ env.FLY_APP_NAME }}.fly.dev Health: ✅"}'
          curl -X POST -H 'Content-type: application/json' --data "$MESSAGE" "$SLACK_WEBHOOK_URL"

      - name: Notify Slack on Failure
        if: failure()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_DEV_INFRA }}
        run: |
          MESSAGE='{"text":"❌ TuneAtLife Portal deployment failed! Version: ${{ github.sha }} Logs: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"}'
          curl -X POST -H 'Content-type: application/json' --data "$MESSAGE" "$SLACK_WEBHOOK_URL"

      - name: Deployment Summary
        if: always()
        run: |
          echo "🎯 Deployment Summary"
          echo "===================="
          echo "Application: ${{ env.FLY_APP_NAME }}"
          echo "Status: ${{ job.status }}"
          echo "URL: https://${{ env.FLY_APP_NAME }}.fly.dev"
          echo "Health Endpoint: https://${{ env.FLY_APP_NAME }}.fly.dev${{ env.HEALTH_ENDPOINT }}"
          echo "Service Principal: ✅ Using AUTOMATION_PAT"
          echo "Authentication: ✅ Using FLY_API_TOKEN"
          echo "Security Scan: ✅ Completed"

  rollback:
    name: Rollback on Failure
    runs-on: ubuntu-latest
    needs: [deploy]
    if: failure()
    steps:
      - name: Setup Fly CLI
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Rollback deployment
        run: |
          echo "🔄 Rolling back deployment..."
          flyctl releases --app ${{ env.FLY_APP_NAME }} --limit 2
          # Get the previous release and rollback
          PREVIOUS_RELEASE=$(flyctl releases --app ${{ env.FLY_APP_NAME }} --json | jq -r '.[1].version')
          if [ "$PREVIOUS_RELEASE" != "null" ]; then
            echo "Rolling back to release: $PREVIOUS_RELEASE"
            flyctl releases rollback $PREVIOUS_RELEASE --app ${{ env.FLY_APP_NAME }}
            echo "✅ Rollback completed"
          else
            echo "⚠️ No previous release found for rollback"
          fi
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Notify Slack of Rollback
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_DEV_INFRA }}
        run: |
          MESSAGE='{"text":"🔄 TuneAtLife Portal deployment failed and rollback initiated. Version: ${{ github.sha }} Please check logs: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"}'
          curl -X POST -H 'Content-type: application/json' --data "$MESSAGE" "$SLACK_WEBHOOK_URL"

